### ISSUE TITLE
Change "Explore related resources" to "Related resources"

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#102]
![Screen Shot 2022-06-30 at 10 30 25 AM](https://user-images.githubusercontent.com/38330843/176744842-5a2c8fad-ac66-4013-8daf-18063fe91867.png)

Curious if we need French copy for this as well, or whether any other strings are missing translation?

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority GitHub issues before launch](https://trello.com/c/rVY120dI/325-high-priority-github-issues-before-launch)

**Comment by dylanzheng94** [comment]
We need to add the french equivalent of "Related resources" to `fr.json`

I can make the code change when given the translation.

**Comment by anikbrazeau** [comment]
Linked to #173

**Comment by anikbrazeau** [comment]
This issue is otherwise resolved.
