### ISSUE TITLE
Update topic design and layout

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#103]
Is it possible to make the yellow line only follow the headings?

Is it possible to allow for paragraphs in the description?

Figma:
![Screen Shot 2022-07-04 at 8 45 50 AM](https://user-images.githubusercontent.com/38330843/177157749-410953db-631e-47a3-ad0e-0bd7e3e9f1d2.png)

Prod:
![Screen Shot 2022-07-04 at 8 46 55 AM](https://user-images.githubusercontent.com/38330843/177157928-d4fdcfbf-ba4a-4c03-af0a-0091f1064ec2.png)

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority GitHub issues before launch](https://trello.com/c/rVY120dI/325-high-priority-github-issues-before-launch)

**Comment by dylanzheng94** [comment]
What do you think about removing the line altogether? 

Current issues:

- User may not understand what the line is for 
- Confuse shorter line for a capital "I"
- Cramped looking on smaller screen

**Comment by anikbrazeau** [comment]
Closing this issue as it is outdated and no longer relevant.
