### ISSUE TITLE
Apply styling to page content

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#104]
Issue found on privacy and terms pages and beyond:
Apply headings 1-3, paragraph, bolding, italics, bullets, links to the legal page

Prod:
<img width="993" alt="Screen Shot 2022-07-04 at 9 47 38 AM" src="https://user-images.githubusercontent.com/38330843/177168130-30414b73-8897-4e37-9ca2-4a083e1b50e2.png">

Contentful:
<img width="689" alt="Screen Shot 2022-07-04 at 9 48 02 AM" src="https://user-images.githubusercontent.com/38330843/177168120-e5c1d45c-db3b-40f5-8c7a-e60538ef0723.png">
s

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority GitHub issues before launch](https://trello.com/c/rVY120dI/325-high-priority-github-issues-before-launch)

**Comment by anikbrazeau** [comment]
This also applies across the site: 

Is it possible to apply all the possible stylings in Contentful rather than a select few? Or is this a big lift or lots of effort? What’s involved?
We can also just prioritize those with a star here if needed:
Paragraph or normal text *
Headings level 1-6 *
Bold *
Italics *
Underline *
Code snippet
Hyperlink *
Bulleted list *
Numbered list *
Block quote
Horizontal line *
Table
Embedded entry
Embedded inline entry
Embedded asset

**Comment by dylanzheng94** [comment]
It's a bit of a lift especially with all the other issues to be done, some styling are easier than others to implement (e.g. headings, bold etc.) while others will require more testing and implementation logic (e.g. embedded assets, code snippet etc)

What is the minimum "must-haves" for the launch that our current content requires and start from there for now

**Comment by anikbrazeau** [comment]
Minimum styling applied, new individual issues have been opened for other outstanding styling tweaks to come:

#134 Revise spacing and indent bullets for easier scanability and readability
#138 Review consistency in components with same functionality (ex: links) 
#170 Line/paragraph breaks in Contentful not displaying in production (About/Contact/Hiring)
#171 Review padding around headings
#172 Review line spacing for resource H1
#180 Consider consistent H1 styling across site
#181 Lists are dense and can be hard to read - increase spacing around lists
#183 Ordered list - size of numbers does not match size of list item text
#184 Revisit hierarchy styles (H4 is smaller than paragraph text)
#189 When screen is narrow, resource H1 is smaller than body text

**Comment by anikbrazeau** [comment]
This appears to be resolved otherwise. @dylanzheng94 do you agree with closing this issue and keeping an eye on the others listed above?

**Comment by daine** [comment]
@anikbrazeau closing this issue as it seems to be resolved & we have a better way to track them in individual issues
