### ISSUE TITLE
Add translation wrapping nomenclature to READ.ME

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#107]
`{{ $t('Text') }}`

What else is involved? Possible to automate in our tests or check that there are no missing translations?

**Comment by anikbrazeau** [comment]
Consider also documenting where to make content changes between `frontend` and `app` for newcomers?

https://github.com/cds-snc/resources-ressources/issues/108

**Comment by daine** [comment]
Link to documentation: https://github.com/cds-snc/resources-ressources#how-to-do-translation-within-the-app

Also some documentation on the `frontend` folder: https://github.com/cds-snc/resources-ressources#what-is-the-frontend-folder
