### ISSUE TITLE
Clarify or consolidate translation .json files

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#108]
There seem to be 2 sets of translation files for each of the EN and FR:

`frontend/locale/en.json`
`frontend/locale/fr.json`
`app/locale/en.json`
`app/locale/en.json`

I’ve been updating both when making content changes, but am curious how it works: are they copies, do we need to update both, or is one redundant? We may want to consider clarifying which one to change when updating copy in our READ.ME or streamline the process in future?

**Comment by anikbrazeau** [comment]
Maybe we can make this a part of the documentation issue #107, @daine, what do you think?

**Comment by daine** [comment]
Closing this as part of #107
