### ISSUE TITLE
Avoid runts in headings, subheadings, and descriptions

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#109]
Runt: Single, short word at the end of a paragraph.

How might we try to eliminate these from happening in blocks of content

![Screen Shot 2022-07-05 at 9 41 16 AM](https://user-images.githubusercontent.com/38330843/177341942-f3d7fa19-e930-422e-82e7-74ce64690f8c.png)

**Comment by daine** [comment]
Grooming notes:
- Some [discussion regarding this](https://stackoverflow.com/questions/31974448/how-can-i-prevent-having-just-one-hanging-word-on-a-new-line-in-an-html-element) 
- Could use `no br` but you would have to input it in all places you don't want this to happen, so maybe not really ideal

**Comment by ClementineHahn** [comment]
Issue was not prioritized and service is now winding down. Therefore closing this without resolution
