### ISSUE TITLE
Documentation on prefixing commit messages

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#111]
When starting to commit in git for the first time, ran into some errors:
![image](https://user-images.githubusercontent.com/38330843/177367282-1a5f91db-a620-4408-bf7a-eaced9cd84cb.png)

Is this a set constraint of our repo or project? Is this something we should add to the documentation for folks onboarding to the team or contributing to the code?

**Comment by daine** [comment]
Updated documentation can be found here: https://github.com/cds-snc/resources-ressources#committing-to-the-repo
