### ISSUE TITLE
Target size of topic link too small

### ISSUE THREAD

**Issue by hillaryl** [cds-snc/resources-ressources#115]
WCAG 2.1 AAA Criterion [2.5.5: Target Size](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html) - target must be at least 44 x 44 CSS pixels. 

Hiring link (text size) is 89x28 px

<img width="506" alt="Screenshot of text on website. Featured. link hiring image of yellow arrow pointing right" src="https://user-images.githubusercontent.com/41651590/177419268-dd3904aa-668e-42c2-9024-726a38ad03f6.png">

Solutions could be to increase the size of the link text or to increase the target area to include a visually identifiable card.

**Comment by anikbrazeau** [comment]
Based on our conversation earlier, is this resolved? Should we close this issue, @dylanzheng94?
