### ISSUE TITLE
Mobile layout cuts off content

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#120]
![Image from iOS](https://user-images.githubusercontent.com/38330843/177763821-bad60f77-34af-42c6-9ecc-b3bab53e0834.png)

![Image from iOS (1)](https://user-images.githubusercontent.com/38330843/177763843-b749d6f5-e0a4-40f3-bf89-146d1f2ec912.png)

**Comment by anikbrazeau** [comment]
Linked to #193

**Comment by anikbrazeau** [comment]
**Checking on this bug in production, using an iPhone 12 mini on Google browser.**

It appears to still be relevant:

- Content cuts off on the right of the screen and the entire content cannot immediately be consumed on the screen at once, including breadcrumbs.
- Horizontal scrolling is possible, if you try, but it's not obvious that it's possible, nor ideal, perhaps?
- Zooming out by pinching the screen causes content to be visible but also reveals other issues -- content then overlaps (ex: language toggle visibly overlaps the header)

See screenshots below: 

![312708639_5167538933346707_139427853722010335_n](https://user-images.githubusercontent.com/38330843/198118446-0d6f38b7-d6bd-4097-b967-41337e4c8835.jpg)
![312899696_841929576935869_6038672967560514820_n](https://user-images.githubusercontent.com/38330843/198118449-693b1414-68ba-48d3-b32b-4ff56f7f5389.jpg)
![306495033_1155670461726595_9222946669188751446_n](https://user-images.githubusercontent.com/38330843/198118450-d41a9941-c7d6-458d-bbaa-7a3a8a736cdf.jpg)
![312817719_525506262316760_6688880921466419911_n](https://user-images.githubusercontent.com/38330843/198118451-9b55f839-0203-4b53-bcac-26f3f0ffd998.jpg)
![306882996_490273356367194_559472762531381587_n](https://user-images.githubusercontent.com/38330843/198118455-cdf6091e-d52b-49ef-92c6-0ad42402b8ec.jpg)
![312753672_637299897941823_2551142551670682410_n](https://user-images.githubusercontent.com/38330843/198118457-a437fc3c-11d8-404e-a481-1cd63dc1fbd3.jpg)

**Comment by anikbrazeau** [comment]
Checking on this bug in staging, using an iPhone 12 mini on Google browser.

# Content is cut off vertically rather than horizontally (in French only?)

- Horizontal cut-off issue is solved but breadcrumbs get overshadowed and cut off by the header component on the French site (does not appear to be an issue in English).
- Cannot read "Accueil" (equivalent of home) because it's cut off by the menu/language toggle.

See screenshots below:

![image](https://user-images.githubusercontent.com/38330843/198120526-0738a4c6-f176-41a8-a34e-9b53aa9a40ae.png)

![image](https://user-images.githubusercontent.com/38330843/198120556-8b484afd-4b6d-4e18-8108-e29538f118c2.png)

![image](https://user-images.githubusercontent.com/38330843/198120589-6c97d418-fea0-4a0d-b947-35ff334bf7b2.png)

**Comment by daine** [comment]
Grooming:
- Can we use conditional styling to move the breadcrumbs menu further down
- While in this ticket, we should decide how to display the nav menu (i. e. it takes up a huge amount of space for mobile users)
