### ISSUE TITLE
French landing page URL-- Update to /accueil instead of fr..../fr

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#121]
Is this expected?

Site uses `fr.learningresources...` and `...xyz/fr`

<img width="1051" alt="Screen Shot 2022-07-07 at 8 06 30 AM" src="https://user-images.githubusercontent.com/38330843/177769595-78d9ba25-dd2d-4025-b57d-188ece679d7c.png">

**Comment by ClementineHahn** [comment]
Linked to closed #118 . Therefore closing this one
