### ISSUE TITLE
[Links] Handling email links across the site

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#133]
`mailto: partnerships-partnariats@cds-snc.ca` link
`mailto: resources-ressources@cds-snc.ca` link

![Screen Shot 2022-07-07 at 3 37 03 PM](https://user-images.githubusercontent.com/38330843/177857873-94fc4058-cdc2-4a7e-8948-74e4de130b8a.png)

**Comment by anikbrazeau** [comment]
@emanelfy do we mean in addition? (I like that! 😃) so long as we're not obscuring the destination. I think Hillary had shared something similar from Adam Silver's blog: [The trouble with mailto email links and what to do instead](https://adamsilver.io/blog/the-trouble-with-mailto-email-links-and-what-to-do-instead/). Eventually, building out a structured contact form might be a solution we explore in the upcoming phase of work?

**Comment by anikbrazeau** [comment]
One thing to consider is that with two email addresses it could get confusing..
![Screen Shot 2022-07-28 at 3 59 02 PM](https://user-images.githubusercontent.com/38330843/181626497-d4ee745b-7df6-4bef-aabb-183bc548900d.png)
.

**Comment by anikbrazeau** [comment]
## About page

EN: `You can reach out to us by [email](mailto:resources-ressources@cds-snc.ca) at resources-ressources@cds-snc.ca.`
FR: `Vous pouvez contacter notre équipe par [courriel](mailto:resources-ressources@cds-snc.ca) à l'adresse suivante : resources-ressources@cds-snc.ca.`

## Contact us page

EN: `To inquire about partnering with us and get coaching and advice, you can [email us](mailto:partnerships-partenariats@cds-snc.ca) at: partnerships-partenariats@cds-snc.ca.`
FR: `Pour en savoir plus sur les possibilités de partenariat et pour obtenir de l’encadrement et des conseils, veuillez communiquer avec nous par [courriel](mailto:resources-ressources@cds-snc.ca) à l'adresse suivante : resources-ressources@cds-snc.ca.`

**Comment by anikbrazeau** [comment]
Similarly, we may want to consider how the underline styling works in tandem with another nearby link. It might be perceived as a broken link by the user here on the About page? Perhaps bolding would be a more effective tactic?

<img width="514" alt="Screen Shot 2022-08-02 at 10 53 08 PM" src="https://user-images.githubusercontent.com/38330843/182514115-b375180b-90ab-49ab-b0da-2e002a9d158c.png">

**Comment by anikbrazeau** [comment]
We may want to adjust our approach to email links across the site.

We are also still using mailto links on the privacy page/terms and conditions for ATIP and the Privacy Commissioner etc.

**Comment by anikbrazeau** [comment]
*This scales across the product

**Comment by anikbrazeau** [comment]
@emanelfy @dylanzheng94 tried to make the change above in Contentful and put a mailto link for email and bold the email address itself, but it just links back to the homepage... Do `mail-to` links require other coding interventions outside the CMS?

**Comment by anikbrazeau** [comment]
Decision in interim: remove hyperlink for now, bold email address.

Change applied to following pages:

- Contact
- About
- Privacy
- Terms

Still need to check: Homepage

**Comment by anikbrazeau** [comment]
Blocked by #195

**Comment by ClementineHahn** [comment]
Blocking issue #195 was never prioritized, therefore this issue can not have resolution. Today service is winding down. As a consequence, closing this issue without resolution .
