### ISSUE TITLE
[Lists] Revise spacing and indent bullets for easier scanability and readability

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#134]
Minor improvement for later when we have more time and bandwidth:

![Screen Shot 2022-07-07 at 4 00 58 PM](https://user-images.githubusercontent.com/38330843/177861647-364da960-0734-479d-8e28-4e11c560c0ac.png)

**Comment by anikbrazeau** [comment]
<img width="1764" alt="Screen Shot 2022-08-03 at 7 53 58 AM" src="https://user-images.githubusercontent.com/38330843/182601640-16a77ebd-dfc6-4eb8-8fee-1ef4c14b7bd2.png">

**Comment by ClementineHahn** [comment]
Issue became irrelevant following multiple iterations of the product and issue would need to be re-assessed and documented again. But service is now winding down, therefore closing this issue without resolution.
