### ISSUE TITLE
Topic H1 sometimes cuts off on mobile 

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#136]
<img width="441" alt="Screen Shot 2022-07-11 at 9 15 19 AM" src="https://user-images.githubusercontent.com/38330843/178272812-5bc1f158-c693-4d02-9973-8f8ac190fef0.png">

**Comment by anikbrazeau** [comment]
Linked to #120
Linked to #193

**Comment by daine** [comment]
Is this still an issue? Needs to be reviewed please 🙏🏼 @anikbrazeau @ClementineHahn

**Comment by anikbrazeau** [comment]
@daine @ClementineHahn  The cutting off seems to be solved. However the size of headings based on levels of hierarchy is not right. The H1 is smaller than H2/3/etc.

![image](https://user-images.githubusercontent.com/38330843/196692554-2efe253c-5f97-4abb-95e3-1839a757eaa6.png)

![image](https://user-images.githubusercontent.com/38330843/196692580-6fa6c706-a9ba-4ea8-8027-be2d98a8faec.png)

![image](https://user-images.githubusercontent.com/38330843/196692603-e4d546d0-3f30-47be-9dfe-88703dbdf2d2.png)

Should we reframe this issue or create a new one?

**Comment by anikbrazeau** [comment]
I will close this and create a new GitHub issue one with the new challenge: #290
