### ISSUE TITLE
When toggle between languages, browser zoom changes

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#153]
When adjusting Zoom in the browser for a page in one language, it is not maintained when switching languages.

For example, when increasing Zoom to 150% in English, and switching to French, it seems to reset the window to default (100%) rather than maintaining the user's preference. Switching back to the original language, switches Zoom again.

**Comment by dylanzheng94** [comment]
@anikbrazeau I believe this is standard behaviour of the browser - to set zoom based on domains.

**Comment by anikbrazeau** [comment]
Oh interesting, because it's viewed as two separate domains? 

I wonder if this might be jarring for public servants who are likely to toggle between languages and think of the site as one entity?

**Comment by anikbrazeau** [comment]
Curious what we think of this as a group @emanelfy @daine any opinions on whether this might be an issue worth investigating or fixing?

**Comment by daine** [comment]
Grooming notes: This is default browser behaviour if there are two different domains. The only way to fix it is to have both french and english be on the same domain (not subdomain). For example, this also exists on our digital.canada.ca and numerique.canada.ca websites @anikbrazeau @emanelfy @ClementineHahn

**Comment by anikbrazeau** [comment]
Thanks for looking into this. I suppose it's a tradeoff of the French first and English first experience -- which I think is important. I will close this issue accordingly, as it's a choice. we've made.
