### ISSUE TITLE
Analytics not differentiating pages

### ISSUE THREAD

**Issue by hillaryl** [cds-snc/resources-ressources#154]
Problem
----
Analytics isn't picking up all actions taken on the website as events. All page title and screen names show up as index_en/fr, topic-topic___en, or Resource | ressource

Page labels are currently autogenerated names of the page component by nuxt/i18n - which gives multiple pages the same names, meaning visits to different pages are counted together.

Page paths are another option but unclear if the query strings are sorting visits to the same page into separate listings.

Possible solution
---
https://online-metrics.com/page-view-in-google-analytics-4/#:~:text=Google%20Analytics%204%20collects%20page,the%20performance%20of%20any%20website.
-> Advanced Report on Page Performance
_**Requires access to Google Tag Manager**_

**Comment by daine** [comment]
I can now confirm that google analytics is recording. More notes here (could contain sensitive information) can be found in this [google docs](https://docs.google.com/document/d/1wz93piiMZ8A4biD5Vr4sNL8BI109zavQcdNwcg196k8/edit#)
