### ISSUE TITLE
Add our site to https://github.com/cds-snc/status-statut

### ISSUE THREAD

**Issue by daine** [cds-snc/resources-ressources#159]
## 📇 User story

As a developer, I want the CDS service status website to track [learning-resources.cdssandbox.xyz](learning-resources.cdssandbox.xyz)

## ✅ Definition of Done
- [x] The [.upptimerc.yml](https://github.com/cds-snc/status-statut/blob/main/.upptimerc.yml#L6-L12) is amended to include the new directive

## 📜 Acceptance criteria
- [x] The [status page](https://status-statut.cds-snc.ca/) shows learning-resources.cdssandbox.xyz

## 📝 Notes
No PRs will be created on this repo, but rather on https://github.com/cds-snc/status-statut
This is a relatively easy task, and you do not need any knowledge of the Learning Resources' tech stack to complete this

**Comment by ShadeWyrm** [comment]
I'd recommend getting an alpha.canada.ca domain before this activity.

**Comment by daine** [comment]
> I'd recommend getting an alpha.canada.ca domain before this activity.

While we are in the process of still figuring out a permanent domain, would it be detrimental if we added our sandbox / staging site to the status page? @ShadeWyrm @maxneuvians @CalvinRodo 

What if we make it clear that it is pre-launch / soft-launch?

Right now we are using uptime robot: https://stats.uptimerobot.com/gP5gohqEVQ

Appreciate the insight ✨

**Comment by CalvinRodo** [comment]
I personally have no issue with you adding your existing domain to the list.

**Comment by sylviamclaughlin** [comment]
This has been done and now learning resources is on the [CDS Status page](https://status-statut.cds-snc.ca/).

**Comment by sylviamclaughlin** [comment]
Ticket/issue has been implemented and learning resources is on the CDS Status page.
