### ISSUE TITLE
Heading spacing consistency / possibly condensing or front-loading content for small screens

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#171]
Spacing appears to be inconsistent across topics and resources. 

Maybe we might find a way to see more of the content upfront by reviewing the amount of space around H1?

![Screen Shot 2022-08-02 at 11 36 02 AM](https://user-images.githubusercontent.com/38330843/182414543-28654efb-a957-4e53-9db9-78fe371da545.png)

![Screen Shot 2022-08-02 at 11 31 47 AM](https://user-images.githubusercontent.com/38330843/182413687-391a8afd-9572-4632-b2a6-0de54ab3b149.png)

![Screen Shot 2022-08-02 at 11 32 52 AM](https://user-images.githubusercontent.com/38330843/182413968-bc5cd87a-f8b6-4b28-8aad-b3e6c1df00e6.png)

<img width="867" alt="Screen Shot 2022-08-03 at 7 27 59 AM" src="https://user-images.githubusercontent.com/38330843/182597170-531ace66-c773-47f0-9be4-0cb5aa1c0b12.png">

**Comment by dylanzheng94** [comment]
@anikbrazeau  yes good point!

**Comment by daine** [comment]
Grooming notes:
Related to #138

**Comment by dylanzheng94** [comment]
So in reviewing this issue, I remember this being a intentional choice for the titles to have greater whitespace. 
The topic page description is closer to the title as I saw the description as being an extension of the title and therefore a "single entity" of sorts. While the resources "meat" of the page was more separated (this also goes for the resource pages)

This was inspired by Samsung's OneUI.

**Comment by anikbrazeau** [comment]
As discussed on Monday, perhaps we can reframe this issue to consider how we might front-load content, especially on smaller/narrower screens. How might we give people information at a glance without having to scroll too much to access main/core content (heading 1 and list of resources).

For example, the title and content are sometimes buried: 

TOPIC (when page loads):
![image](https://user-images.githubusercontent.com/38330843/201108139-68c13a3d-a501-4cf6-a161-8b68afa6564c.png)

RESOURCE (when page loads):
![image](https://user-images.githubusercontent.com/38330843/201108029-16f9e89e-bbe9-4c97-b9b4-8c871eda91ed.png)

RESOURCE (when scroll down):
![image](https://user-images.githubusercontent.com/38330843/201108288-cd2af577-d3f3-420f-baa3-be2fcfb952c8.png)

**Comment by anikbrazeau** [comment]
Linked to #248

**Comment by ClementineHahn** [comment]
Was resolved by #248
