### ISSUE TITLE
Consider consistent H1 styling across site

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#180]
Is the different styling of H1 on different pages intentional? 

<img width="1014" alt="Screen Shot 2022-08-02 at 9 34 45 PM" src="https://user-images.githubusercontent.com/38330843/182505297-7a7bd36b-d5c1-47f7-a923-c3ed454c7ba1.png">

<img width="1028" alt="Screen Shot 2022-08-02 at 9 35 27 PM" src="https://user-images.githubusercontent.com/38330843/182505301-90122dd8-58fa-44c7-8b99-3ccb6921170f.png">

**Comment by anikbrazeau** [comment]
**Hiring** (and resource pages) seem to be `font-bold text-4xl sm:text-5xl`
**Contact us** (and footer pages) seem to be `class="font-bold text-4xl my-14"`

**Comment by dylanzheng94** [comment]
@anikbrazeau Not intentional - will component-ize the heading to ensure heading consistency moving forward thank you

**Comment by anikbrazeau** [comment]
On a narrow viewport, H1 and H2 appear to be the same size? Perhaps there's a way to instill more visual hierarchy to differentiate these levels? 

![Image](https://user-images.githubusercontent.com/38330843/208750539-5cdeac5b-001f-45b4-a983-f91856910a6c.png)

**Comment by dylanzheng94** [comment]
Done
