### ISSUE TITLE
Linked text with a mix of styles (ex: italics and non-italics, or bold and non-bold, or italics and bold) disappears

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#182]
On the Privacy page for example, this means entire strings are missing in production. 

See the link in the following sentence in EN+FR: `When a threat to Canadian Digital Service websites or computer systems of the Government of Canada is detected, information is collected pursuant to [section 161 of the Financial Administration Act](https://laws-lois.justice.gc.ca/eng/acts/f-11/FullText.html#s-161.).`

<img width="1762" alt="Screen Shot 2022-08-02 at 9 49 27 PM" src="https://user-images.githubusercontent.com/38330843/182506698-193e8d78-7aae-43ac-9b99-a20b69d60e47.png">

<img width="1780" alt="Screen Shot 2022-08-02 at 11 16 31 PM" src="https://user-images.githubusercontent.com/38330843/182516696-3f0337ac-866e-4961-b2f0-919708abadcf.png">

<img width="1762" alt="Screen Shot 2022-08-02 at 11 16 53 PM" src="https://user-images.githubusercontent.com/38330843/182516699-b858bb30-879f-4ba4-b54c-e6f49f0132f6.png">

Is this fixable or should we dial back styling in Contentful?

**Comment by anikbrazeau** [comment]
Since this only happens when a combination of styling is applied within an embedded hyperlinked string.

For now, I've opted to remove the italics across the entire link to ensure text does not disappear, but perhaps we can find a more elegant solution or remove content creators' ability to have that option?

**Comment by ClementineHahn** [comment]
Problem was not prioritized. Issue closed
