### ISSUE TITLE
Contextualize "Resources" and "Collection" pages

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#185]
Better contextualize the specific CDS context and expected use and application.
Make the interpretation and translation of resources externally clearer.

Solving: https://docs.google.com/document/d/1SZveZSky80zJOwkeosOoZLh4UWfsEQrIbidJYOMoRRI/edit#heading=h.gr8mvulji4pn

Linked to: https://github.com/orgs/cds-snc/projects/16/views/2?filterQuery=&pane=issue&itemId=15731044

**Comment by ClementineHahn** [comment]
Duplicate with #464 . Was worked on and resolved .
