### ISSUE TITLE
Links width fit-content not working

### ISSUE THREAD

**Issue by daine** [cds-snc/resources-ressources#198]
> `w-fit` doesn't actually perform `style="width: fit-content"` another solution is required

Thanks for flagging this! The [Content Security Policy for styles](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src) doesn't like inline styles, so we might have to look further into this. I'm not seeing any errors right now on https://learning-resources.cdssandbox.xyz/ but I'll check our CSP report this week

_Originally posted by @daine in https://github.com/cds-snc/resources-ressources/issues/166#issuecomment-1208295799_

**Comment by dylanzheng94** [comment]
This seems to have been fixed after updating the NPM package for tailwind css.
