### ISSUE TITLE
Content Security Header reporting directive

### ISSUE THREAD

**Issue by daine** [cds-snc/resources-ressources#201]
## 📇 User story

As a developer, I want the CDS security policy to track and report our Content Security Policy failures, so that I can remedy any security issues in a timely manner.

## ✅ Definition of Done
- [ ] The [CSP](https://github.com/cds-snc/resources-ressources/blob/staging/customHttp.yml) is amended to include the new directive

## 📜 Acceptance criteria
- [x] CSP is passing (could be viewed [using a browser extension](https://developer.chrome.com/docs/apps/contentSecurityPolicy/))
- [x] https://csp-reports.security.cdssandbox.xyz shows a report for Learning Resources

## 🛡More info
Add `report-uri https://csp-report-to.security.cdssandbox.xyz/report;` to the CSP

https://gcdigital.slack.com/archives/C5SGXCMEY/p1659725004520219
> Hi everyone. We've launched a new security service to help teams track [Content Security Policy (CSP)](https://portswigger.net/web-security/cross-site-scripting/content-security-policy) failures. You can find it [here](https://csp-reports.security.cdssandbox.xyz/) behind the CDS secure proxy. All that's required to integrate with this service is to add the `report-uri https://csp-report-to.security.cdssandbox.xyz/report;` directive to your existing CSP as shown [here](https://github.com/cds-snc/scan-files/commit/ad6c4fbffa463e13b646900e2c50d88cabc1cf07). This is an early prototype and may be rough around the edges as it gets put through its paces.

**Comment by sylviamclaughlin** [comment]
@daine Based on the slack thread, it seems that the content_security_policy setting has to be added to the headers policy in Cloudfront. As far as I can tell, cloudfront is not configured for learning resources, but please correct me if I am wrong. Are there any plans to add cloudfront? If not, then not sure if this can be implemented.

**Comment by daine** [comment]
@sylviamclaughlin we define our custom headers, which contains the content security policy [in this file](https://github.com/cds-snc/resources-ressources/blob/staging/customHttp.yml). I believe this is just a matter of adding the line `report-uri https://csp-report-to.security.cdssandbox.xyz/report;` to https://github.com/cds-snc/resources-ressources/blob/4fcfb2cacaf25d411ed81624c13a593c52df9f01/customHttp.yml#L13

**Comment by sylviamclaughlin** [comment]
Thanks for the explanation @daine! I will take a look at the custom headers file.

**Comment by sylviamclaughlin** [comment]
[Pull Reques](https://github.com/cds-snc/resources-ressources/pull/274)t with the change has been created.

**Comment by sylviamclaughlin** [comment]
This task has been done and now all the learning resources sites (staging, production plus french versions) shows up reports [here](https://csp-reports.security.cdssandbox.xyz/).
