### ISSUE TITLE
Pages fail to load on link click when using GC Wifi

### ISSUE THREAD

**Issue by hillaryl** [cds-snc/resources-ressources#223]
**Note:** This is a relatively involved issue, with most of the complexity lying in the ability to coordinate and replicate the issue.

**Issue:**
When connected to the internet via GC Wifi, website won't load at all when browsing in Chrome incognito mode, nor Firefox with the cache cleared. 

- Chrome incognito returns Unsupported protocol error: "The client and server don't support a common SSL protocol version or cipher suite."
- Firefox returns SSL_ERROR_NO_CYPHER_OVERLAP (secure connection failed).

![Firefox_error](https://user-images.githubusercontent.com/41651590/185407776-f158b108-ee03-4062-9679-0c1fb3f815e8.gif)

Website will load when using Chrome without the cache cleared, but inconsistently. Some links don't work, others do.

![Chrome](https://user-images.githubusercontent.com/41651590/185407819-38f5d3df-ddd3-4eae-8d6c-f1aa736a605d.gif)

Can't seem to reproduce outside the GC Wifi network.

**Comment by anikbrazeau** [comment]
Possible similarity to previous bug/issue observed #129, maybe? 🤷‍♀️

**Comment by maxneuvians** [comment]
I think this is because GC WIFI does not support exclusively TLS 1.3 connections and requires TLS 1.2 to be available as well. That, however, was a problem in the past so this might have a different cause, although it does sound similar.

**Comment by CalvinRodo** [comment]
I think Max is correct, my best guess is that this is an issue with the devices that SSC is using for network monitoring and TLS 1.3, either the device doesn't support it or it's causing an issue with the way the devices do packet inspection.

**Comment by maxneuvians** [comment]
<img width="990" alt="Screen Shot 2022-08-17 at 4 54 43 PM" src="https://user-images.githubusercontent.com/867334/185241254-2fd2f82e-ab06-4eb6-bd05-f26ee34f5019.png">

It does support TLS 1.2 but it does not support things like old IE and Safari, but there is something in the network that is using older cyphers 

https://www.ssllabs.com/ssltest/analyze.html?d=learning%2dresources.cdssandbox.xyz&s=108.138.94.50&hideResults=on&latest

**Comment by emanelfy** [comment]
Further validation:
I'm currently at the GC Co-working space in Toronto, and just tested out visiting the sub-pages **+ the language toggle to French** and got the following errors:
<img width="1637" alt="Screen Shot 2022-09-14 at 1 33 04 PM" src="https://user-images.githubusercontent.com/35348560/190224146-f317f8db-0c55-4217-921d-aa2a0b971715.png">
<img width="1635" alt="Screen Shot 2022-09-14 at 1 32 24 PM" src="https://user-images.githubusercontent.com/35348560/190224160-f6a30820-cc6f-45f4-b412-7a8d61d794fe.png">
<img width="1635" alt="Screen Shot 2022-09-14 at 1 31 52 PM" src="https://user-images.githubusercontent.com/35348560/190224167-ec154625-51e1-43a6-bcc0-a8b21187ef78.png">

**Comment by anikbrazeau** [comment]
Potential solution proposed in [incident review](https://docs.google.com/document/d/1bbJPzL28zCIDTdvN1gva_RnT-LxJh67zPvPWML7rBaQ/edit) (w/Daine, Clem, Eman): 

> Move away from `cdssandbox.xyz` domain --> `alpha.canada.ca`

**Comment by daine** [comment]
Grooming notes: 
This should fixed by
- #289

**Comment by ClementineHahn** [comment]
Product was migrated to new domain alpha.canada.ca #289 . It did resolve the issue
