### ISSUE TITLE
Refactor HTML divider comments

### ISSUE THREAD

**Issue by dylanzheng94** [cds-snc/resources-ressources#233]
It seems like Github does not like the following comment format 
`<!-- [Text] ---------->`

Please reformat all HTML divider comments to look like the following:
`<!-- [Text] =========-->`

**Note:** This is relatively easy, and a good starter issue.

**Comment by anikbrazeau** [comment]
@dylanzheng94 is this complete? can we close this issue?

**Comment by dylanzheng94** [comment]
done
