### ISSUE TITLE
Website menu

### ISSUE THREAD

**Issue by dylanzheng94** [cds-snc/resources-ressources#241]
## 📇 User story

As a user, I want to have a website menu, so that I can find or browse to new topics without the need to return home.

## ✅ Definition of Done
- [x] Feature is in staging
- [x] Feature documentation is complete
- [x] Feature checked for accessibility violations
- [x] Code reviewed and passing

## 📜 Acceptance criteria
- [ ]

**Comment by daine** [comment]
Fixes needed:
- [ ] #259 Topic / Menu not working locally (with npm run dev / on localhost:3000)

**Comment by anikbrazeau** [comment]
@dylanzheng94 @daine is it fair to say this issue is complete? might this be one we can close?

**Comment by dylanzheng94** [comment]
Done
