### ISSUE TITLE
Local development not working as intended

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#243]
**Describe the bug**
Navigating away from landing page on `localhost:3000` gives an error:

```
ℹ Waiting for file changes                                                                                                                      12:44:14
ℹ Memory usage: 565 MB (RSS: 851 MB)                                                                                                            12:44:14
ℹ Listening on: http://localhost:3000/                                                                                                          12:44:14
-- en/index.vue | locale: en-CA                                                                                                                 12:44:17

 ERROR  Cannot read properties of undefined (reading 'includes')                                                                                12:44:21

  at asyncData (_topic.vue:145:0)
  at promisify (.nuxt/utils.js:314:0)
  at server.js:4513:82
  at Array.map (<anonymous>)
  at module.exports../.nuxt/server.js.__webpack_exports__.default (.nuxt/server.js:269:0)`
```

**To Reproduce**
1. Set up locally
2. In terminal: `npm run dev` 
3. On `localhost:3000` and click on "Hiring"
5. A different error appears when click "Français"

**Expected behavior**
Topic > Resources, page loading content

**Screenshots**
![image](https://user-images.githubusercontent.com/38330843/191350952-1ca7eefe-0e73-4c43-8973-82a456b685a6.png)

<img width="682" alt="Screen Shot 2022-09-20 at 3 48 08 PM" src="https://user-images.githubusercontent.com/38330843/191351410-30f17ee4-40fc-4d64-8815-fb16f85e24e9.png">

<img width="732" alt="Screen Shot 2022-09-20 at 3 48 02 PM" src="https://user-images.githubusercontent.com/38330843/191351432-082d4df7-4eb8-4395-9d05-5c58a78970df.png">

<img width="1666" alt="Screen Shot 2022-09-20 at 3 58 23 PM" src="https://user-images.githubusercontent.com/38330843/191352818-ebbde28d-a763-4053-8649-39457b7754f5.png">

**Desktop (please complete the following information):**
 - MacOS, Chrome 

**Additional context**
Daine and Anik have both tested locally, with similar result.

**Comment by daine** [comment]
This issue is caused by the locale not being properly set (only happens in dev environment). [This code fixes this issue.](https://github.com/cds-snc/resources-ressources/pull/249/files#diff-a035d3d5059d0fad37c353017930cae70781246c411089ed5c435b62fb1f328cL131-L144)
