### ISSUE TITLE
[Spacing] Consistency in separate paragraphs

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#253]
**Describe the bug**
Spacing around paragraphs or line breaks in general appear inconsistently / not as expected or displayed in the text editor within Contentful. If possible, would be great to have greater reliability with editor and site for content confidence?

**To Reproduce**
1. Go to Contentful
2. Write a paragraph
3. Apply bold or bullets or any styling to the text following
4. See how it renders on site.

**Expected behavior**
Match text editing happening in Contentful.

**Screenshots**
![Screen Shot 2022-09-21 at 9 44 48 PM](https://user-images.githubusercontent.com/38330843/191640377-b23a65aa-7300-416b-b3fa-929342e09a01.png)

Linked to #104 #134 #181

**Comment by anikbrazeau** [comment]
Check for WCAG compliance with regard to:

> **_PERCEIVABLE_ 1.4 Distinguishable:** For paragraphs, line spacing is at least 1.5 times the font size and paragraph spacing is at least 1.5 times the line spacing

**Comment by dylanzheng94** [comment]
Done
