### ISSUE TITLE
Unexpected tabbing order between menu and language switcher

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#269]
**Describe the bug**
When clicking through the "Topics" menu, the first item that gets focus is "Français" which is outside the menu.

**To Reproduce**
1. Go to staging.
2. Tab through elements with keyboard.
3. Click 'Enter' when get to 'Topics' menu.
4. Tab again.

**Expected behavior**
Go through elements in menu sequentially.
Ideally, focuses on 'Agile', 'Design', 'Hiring', and 'UX research' before 'Français'

**Screenshots**
<img width="311" alt="Screen Shot 2022-09-28 at 10 54 01 PM" src="https://user-images.githubusercontent.com/38330843/192928296-3a2454a4-f5e8-483f-b452-8506ac40164d.png">

**Desktop (please complete the following information):**
 - Mac, Google Chrome

**Additional context**
Found during manual a11y checks with keyboard.

**Done when:**
The behaviour matches the expected behaviour

**Comment by dylanzheng94** [comment]
Issue has been fixed in staging
