### ISSUE TITLE
Add fonts to content security policy

### ISSUE THREAD

**Issue by daine** [cds-snc/resources-ressources#285]
## 📇 User story

As a developer, I want to my content security police to load google fonts, so that I can use the fonts in the site.

## ✅ Definition of Done
- [ ] CSP is amended to allow google fonts

## 📜 Acceptance criteria
- [ ] No CSP violations are showing up for fonts

## 📝 More info
<img width="1182" alt="Screen Shot 2022-10-04 at 5 05 20 PM" src="https://user-images.githubusercontent.com/916044/193952283-5ff41d89-cf3f-4832-b3e2-0db5c937d6f4.png">

https://content-security-policy.com/examples/google-fonts/

**Comment by sylviamclaughlin** [comment]
Closing this issue since it has been resolved. (https://github.com/cds-snc/resources-ressources/pull/324)
