### ISSUE TITLE
[Headings] Size of section titles does not match intended hierarchy (H1 is smaller than H2/3/etc.)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#290]
On mobile, the size of headings based on levels of hierarchy is not right. The H1 is smaller than H2/3/etc.

![image](https://user-images.githubusercontent.com/38330843/196692554-2efe253c-5f97-4abb-95e3-1839a757eaa6.png)

![image](https://user-images.githubusercontent.com/38330843/196692580-6fa6c706-a9ba-4ea8-8027-be2d98a8faec.png)

![image](https://user-images.githubusercontent.com/38330843/196692603-e4d546d0-3f30-47be-9dfe-88703dbdf2d2.png)

**Comment by anikbrazeau** [comment]
@dylanzheng94 has this been completed? should we close this issue?

**Comment by dylanzheng94** [comment]
completed
