### ISSUE TITLE
[Jump-to] Add top padding when jumping to a particular section with anchor links

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#293]
I wonder if it'd be possible to add some space/padding to the text when jumping to a particular section? For ease of readability, maybe it could be aligned with the start of "On this page" rather than the very top of the browser window? 

![Screen Shot 2022-09-21 at 9 59 16 PM](https://user-images.githubusercontent.com/38330843/191641777-ad0fb34b-5ecf-4d71-8ac7-35696063c08a.png)

_Originally posted by @anikbrazeau in https://github.com/cds-snc/resources-ressources/issues/239#issuecomment-1254416699_

**Comment by anikbrazeau** [comment]
Linked to #295

**Comment by dylanzheng94** [comment]
Heading now aligned with "On this page" in staging
