### ISSUE TITLE
Hide "related resources" when field is empty

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#299]
**Describe the bug**
If a resource has no related resources the heading still shows up.

**To Reproduce**
1. Add a new resource
2. Don't link related resources
3. Publish and deploy staging
4. See empty state

**Expected behavior**
If a field is empty it is expected that it should be hidden

**Screenshots**
![Screenshot 2022-10-27 at 1 30 04 PM](https://user-images.githubusercontent.com/38330843/198359155-c0407399-b662-41d2-918f-2cbb95014094.png)

**Other**
Linked to #251

**Comment by anikbrazeau** [comment]
Tested to check relevance. This is still an issue: 
<img width="1420" alt="Screenshot 2022-12-15 at 11 45 43 AM" src="https://user-images.githubusercontent.com/38330843/207919073-f3e93c6f-4a13-490f-a64b-47b4026d6363.png">

**Comment by dylanzheng94** [comment]
Done
