### ISSUE TITLE
Change name of website to reflect web address change

### ISSUE THREAD

**Issue by dylanzheng94** [cds-snc/resources-ressources#302]
## 📇 User story

As a user, I want to the name of the website to be reflective of the web address, so that I am not confused.

## ✅ Definition of Done
- [ ] Website work mark reflects the web address
- [ ] Landing page text reflects the web address

## 📜 Acceptance criteria
- [ ] Preview is reviewed

**Comment by anikbrazeau** [comment]
Maybe we can discuss this at our next Dev-Design Sync? cc @janicelagiorgia @emanelfy 
I'm not sure the change in Domain requires us to change the name of the site?

**Comment by daine** [comment]
Grooming notes: Possibly a non-issue
