### ISSUE TITLE
[Spacing] - Line breaks do not appear predictably on the site as they do in Contentful - WYSIWYG Mismatch

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#303]
**Describe the bug**
While it is possible to create a linebreak / spacing between two body paragraphs, it requires additional experimentation to do a Shift+Enter rather than simply Enter.

**To Reproduce**
1. Go to Contentful
2. Publish a resource with two paragraphs
3. Redeploy staging
4. See error -- text will appear as one big paragraph

**Expected behavior**
Matching Contentful + website behaviour

**Screenshots**

<img width="1748" alt="Screenshot 2022-10-28 at 3 31 32 PM" src="https://user-images.githubusercontent.com/38330843/198717651-1b1edc17-d581-4410-932e-fd9aec85efcd.png">

**Comment by anikbrazeau** [comment]
Related to #152 #253

**Comment by anikbrazeau** [comment]
This is still an issue: 

<img width="972" alt="Screenshot 2022-12-20 at 11 11 23 AM" src="https://user-images.githubusercontent.com/38330843/208713312-dafdab5e-4364-4d28-b152-01e95e1be6bc.png">

**Comment by dylanzheng94** [comment]
Done
