### ISSUE TITLE
Redeploying causes temporary error?

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#305]
**Describe the bug**
Shortly after redeploying staging, I seem to encounter an error when trying to access resources. Wondering if this is repeatable? And if it's something other users might experience?

**To Reproduce**
1. Go to staging and navigate to X resource
2. Go to Contentful, publish a new change to X resource
3. Go to AWS, redeploy the staging site
4. See error on staging when trying to navigate the site

**Expected behavior**
Is this expected? Is there a way to prevent it?

**Screenshots**

When clicking on "Establishing team rituals" from the "Agile" topic page:
<img width="1475" alt="Screenshot 2022-10-31 at 1 01 56 PM" src="https://user-images.githubusercontent.com/38330843/199066484-ef112ab4-e945-4fd2-9f0b-59cbdc15d802.png">

**Desktop (please complete the following information):**
 - MacOS / Chrome

**Comment by anikbrazeau** [comment]
This just happened again -- 

![Screenshot 2022-10-31 at 4 21 47 PM](https://user-images.githubusercontent.com/38330843/199103182-e56957ed-3d43-4260-88b1-4c18e87e95b2.png)

**Comment by anikbrazeau** [comment]
@daine, as per Friday's request, I tried testing to see if this was still happening... but the build failed so wasn't able to assess whether it's still an issue: 

<img width="322" alt="Screenshot 2022-11-07 at 8 31 30 AM" src="https://user-images.githubusercontent.com/38330843/200322923-54c59064-366e-4350-8c29-27680731050d.png">

**Comment by daine** [comment]
@anikbrazeau I've done lots of work on the code that should get rid of that `includes` issue. Definitely bug squashing. I don't think this is an issue anymore but please confirm 🙏🏼

**Comment by anikbrazeau** [comment]
Closing this issue as it appears to be resolved.

**Comment by daine** [comment]
Update: renaming title of this ticket as it the issue had nothing to do with redeployments
