### ISSUE TITLE
Solidify the two-week agenda/scheduling for our "restrategization" sprint

### ISSUE THREAD

**Issue by emanelfy** [cds-snc/resources-ressources#307]
Will add link to draft agenda doc here when it is shared with the team tomorrow morning (Tuesday Nov 1st) for input and feedback.

This scope of work will also include the rough deck outline for our shareback presentation to Jessie/sr. mgmt, and the prep work for my first 1:1 with Jessie.

[Service team overview doc](https://docs.google.com/document/d/1BObAtQTpz9LIQJZdzKyqfIQb1FSNPhf-c7JdoPovvsA/edit) that I created last sprint has already been shared with Jessie ahead of our 1:1 (as of last Friday, Oct 28th).

**Comment by anikbrazeau** [comment]
[Skeleton Agenda](https://docs.google.com/document/d/10cPRSVUpxgsvFSThCGO6o0Mtdl2aErgZCPBPShX6cEw/edit#)
