### ISSUE TITLE
Refactor path prefix strings into a variable

### ISSUE THREAD

**Issue by daine** [cds-snc/resources-ressources#320]
## 📇 User story

As a developer, I want to refactor the way we set paths so that there is less risk in changing paths.

When changing the name for the topic path in french, there were additional inconsistencies that made it harder to implement.

**See the following commits:**
https://github.com/cds-snc/resources-ressources/pull/319/commits/cb54e9fc4e2c7b4594b1360d4edb9e9d12fd32e3
https://github.com/cds-snc/resources-ressources/pull/311/files

## ✅ Definition of Done
- [ ] Implement DRY and KISS principles; don't have multiple strings of the same thing in more than 2 places in the code

## 📜 Acceptance criteria
- [ ] Code is clean
- [ ] Code is reviewed & tested

**Comment by anikbrazeau** [comment]
Would the essence here be to ensure the path matches the name of the page even as we iterate on it? 

Might this also apply to resources in Contentful? If a resource title changes, does the URL change automatically? does the old URL redirect to the new URL?

**Comment by daine** [comment]
@anikbrazeau 

> Would the essence here be to ensure the path matches the name of the page even as we iterate on it?

I'm not sure if I'm getting the question right, but this ticket ensures that when we have one authoritative variable for setting a path. We have been calling this the `page_prefix` or `path_prefix`, or some variation of `<content model>_prefix`

> Might this also apply to resources in Contentful? If a resource title changes, does the URL change automatically? does the old URL redirect to the new URL?

This only applies to the prefixes at the moment, so changing the title in contentful is unrelated to the specifics of this ticket.

I've updated the title to make it a bit more clear 😅

**Comment by daine** [comment]
Fixed in #401
