### ISSUE TITLE
Production site does not sort topics alphabetically

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#321]
(Not sure if a PR in the works already addresses this since it's just for prod?)

Staging automatically reshuffles topics to be listed from A-Z for a predictable and expected ordering system.

While Production does not. It puts last updated first, which switches the order often.

<img width="1400" alt="Screenshot 2022-11-04 at 11 11 09 AM" src="https://user-images.githubusercontent.com/38330843/200010540-ba16e01c-3f9b-49c9-846e-5263f0028914.png">

**Comment by dylanzheng94** [comment]
This is because we have no merged staging into prod yet, the ordering will be there when we do the merge.
@anikbrazeau Is it okay if I close this issue?

**Comment by daine** [comment]
@anikbrazeau I think this was already done in #262 but you're right it's still in staging

**Comment by anikbrazeau** [comment]
Resolved as #239 was merged
