### ISSUE TITLE
About page: Clarifying CDS Learning Resources

### ISSUE THREAD

**Issue by emanelfy** [cds-snc/resources-ressources#327]
Work happening [in this doc](https://docs.google.com/document/d/1kKmG6p0ICi5PGvIHAcxDGODoLwbpEH-bBdZLSBA9hqk/edit?usp=sharing).

**Comment by emanelfy** [comment]
Requires review / feedback from the team, and then translation once we're satisfied before it can be added on staging.

**Comment by emanelfy** [comment]
Making some updated changes to this before publishing, based on our outcomes from Re-Strat.

**Comment by anikbrazeau** [comment]
Clean version sent to Linguistic Services, here: https://docs.google.com/document/d/1vWrRkzxI8KLejmmqyGD50tU-iFDmOP11MZmjd_jf4qA/edit#heading=h.tb8npm2fvkn0

Requested return: Tuesday December 20, 2022.

**Comment by anikbrazeau** [comment]
NOW LIVE: https://resources.alpha.canada.ca/about

Updated bilingually in Contentful. Redeployed to Sandbox, Staging and Production.

Shared with team: https://gcdigital.slack.com/archives/C02L8T619L2/p1671556057499479
Follow-up items: #170 #253 #303 to correct lack of paragraph spacing
