### ISSUE TITLE
[Breadcrumbs] Should breadcrumbs reflect user's path via "collections"?

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#328]
**Describe the bug**
When using collections to arrive at a page/resource, the user's path taken is not reflective of the navigation. This mismatch causes confusion and prevents the user from retracing their steps

**To Reproduce**
1. Go to Hiring digital > Responsibilities "collection"
2. Click on Product manager responsibilities
3. Try to navigate back, notice the breadcrumbs
OR
4. Go to Agile development > Activities "collection"
5. Click on Product manager activities
6. Try to navigate back, notice the breadcrumbs

**Expected behavior**
Expect to be able to retrace steps, for breadcrumbs to dynamically reflect my journey.

**Comment by dylanzheng94** [comment]
@anikbrazeau 

https://www.nngroup.com/articles/breadcrumbs/

![Image](https://user-images.githubusercontent.com/11035629/204017135-f339d75e-9c59-41e8-ad62-007b7e247de9.png)

I'd say the current behaviour of the site is in-line with the guidance provided by the post above as well as inline with the practices other websites.

**Comment by emanelfy** [comment]
Discussion: is this something we should continue to pursue? 

This emerged from usability testing. Each resource has a "home" but might also be referenced in a collection elsewhere. When users click through the website, if it's a referenced resource it'll go to its home but not the path a user clicked through to get there. 

Breadcrumbs would highlight where the resource is, not the path taken to get there. 

Dylan: not something we need to pursue, it's intended purpose is working.

Anik: this is framed as a breadcrumb issue, but maybe it needs to be broadened to something like "help users retrace their steps" – someone landed somewhere and they were just trying to get back, the connections weren't obvious enough. An alternate solution might be required, this will become crucial as we scale. What's connected to what, etc.
