### ISSUE TITLE
Refine team values and design principles

### ISSUE THREAD

**Issue by janicelagiorgia** [cds-snc/resources-ressources#333]
# Context 

We need to close the loop on restrategization week(s) and forge ahead with our values and principles in mind.

# Done when

- We have met, discussed overlap, articulated and agreed upon values/principles to help us make decisions going forward.
- We have divided up the remaining work in order to close the loop on these two initiatives.

# Links

- [Research refresh](https://docs.google.com/presentation/d/1GRPrn44X5LIFPpXaUzrk_5qZtFTuFQfpH12sWM2Ikx4/edit?pli=1#slide=id.gfd02988409_3_56)
- [Team Values](https://miro.com/app/board/uXjVPDJv_Ns=/)
- [Design Principles](https://miro.com/app/board/uXjVPB98MyU=/)
- [Vision](https://miro.com/app/board/uXjVPCgt5VU=/)

**Comment by anikbrazeau** [comment]
Latest summarized here: https://docs.google.com/document/d/1fdkRZlewKP6Sg_yc2cZxWSrtHGfNbyZTkwvyTnHNmsM/edit#bookmark=id.38aetz820fgi

**Comment by anikbrazeau** [comment]
@janicelagiorgia anything to add re: team values? or should we fold this into the content strategy task?
