### ISSUE TITLE
Bug: Link to other resource displays as entry-hyperlink id #

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#337]
**Describe the bug**
Hyperlink in 'body' not rendering.

**To Reproduce**
1. Go to Agile > Principles for how product teams build services
2. Cmd+F: `entry-hyperlink id: 2JOB1jT6uYOowc8OVhiEDx`
3. See error

**Expected behavior**
Matching Contentful inputs: embedded hyperlink
<img width="921" alt="Screenshot 2022-12-07 at 8 21 44 AM" src="https://user-images.githubusercontent.com/38330843/206190517-7c582d49-4fe9-4f3d-9150-c58c8670f2e1.png">

**Screenshots**
<img width="1250" alt="Screenshot 2022-12-07 at 8 20 29 AM" src="https://user-images.githubusercontent.com/38330843/206190630-fcdd5020-e785-4024-b9f6-0428473371ae.png">

**Desktop (please complete the following information):**
 - OS: Ventura
 - Browser Chrome
 - Version 107

**Additional context**
Perhaps worth checking if this happens anywhere else also?

**Comment by dylanzheng94** [comment]
Issue has been fixed, will close
