### ISSUE TITLE
Create / finalize Objectives for Alpha 2

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/resources-ressources#340]

**Comment by ClementineHahn** [comment]
Current updated roadmap for team to consider is here . [
](https://docs.google.com/document/d/1glGmau3wr-LKK9rz8vkYf_XgTkSM8IB2xgcRQtj7npw/edit#)

**Comment by anikbrazeau** [comment]
Latest doc here: https://docs.google.com/spreadsheets/d/17NNSU669xhnTL9zq5USZLSUTeK_HRxVYufT7yW3nafc/edit#gid=873829001

**Comment by emanelfy** [comment]
Original doc renamed "objectives for the team" and our roadmap now lives in a new tab in the spreadsheet linked above. The objectives doc is done and in a good place. The roadmap will continue to be iterated on, the team will be meeting about it next Monday January 9th.
