### ISSUE TITLE
Breadcrumbs missing on some pages and can't be located on others

### ISSUE THREAD

**Issue by hillaryl** [cds-snc/resources-ressources#349]
📆 **Study info**

Information architecture usability testing - October 2022 - Facilitator: @ClementineHahn 

## 🚦 Issue severity 

🔶 Moderate – Yes, after overcoming significant difficulty and/or confusion.

## 📝 What happened?

The participant was on the about page and wanted to go back to the home page. At that point they could not find a link that would take them home, noting that breadcrumbs were absent. They looked at each of the links in the footer to see if anything there might help them, and ultimately ended up clicking the back button. It took them about 10 extra seconds to figure out what to do.

The same participant encountered the same issue later on when trying to navigate from the bottom of the Designer SOMC page to the home page - the breadcrumbs at the top of the page had disappeared due to scrolling, while the sticky header remained. 

## 💬 In the participant's own words

"Once in about, then contact us , there is no breadcrumb anymore, how do i get back to home?”

## 📗 User story

As a public servant, I need breadcrumbs to be visible wherever I am on a page, so that I can navigate back to where I was before.

## 📜 Recommendations

- Include breadcrumbs on auxiliary pages (about, contact, privacy etc.) 
- Make breadcrumbs persistently available even after scrolling

## ℹ️ More info
Two participants weren't aware that the Learning Resources logo was a link that would take them back to the home page. This isn't an issue that needs to be fixed, just a note that it's not a universally known way of navigating to home.

**Comment by anikbrazeau** [comment]
Potentially related to adding navigational features to auxiliary pages #292

**Comment by anikbrazeau** [comment]
Potentially related to #272 for losing breadcrumbs while scrolling

**Comment by dylanzheng94** [comment]
Done
