### ISSUE TITLE
Content designer SOMC resource not generated

### ISSUE THREAD

**Issue by dylanzheng94** [cds-snc/resources-ressources#353]
**Describe the bug**
'Content designer statement of merit criteria resource is not being generated.

**To Reproduce**
1. Go to 'Hiring Digital' -> 'Designers' -> 'Content designers'
2. Notice that 'Content designer statement of merit criteria is not there

**Expected behavior**
'Content designer statement of merit criteria' resource should be present.

**Additional context**

**Comment by anikbrazeau** [comment]
@dylanzheng94 
This is in progress, I think it's related to #313. 
I'll unpublish for now, redeploy, and republish once all the links are available.

**Comment by anikbrazeau** [comment]
Resolved in the interim --
