### ISSUE TITLE
[Jump-to] Scrolling through jump-to link sections highlights the following section before arriving

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#356]
**To Reproduce**
1. Go to a resource with long content ex: designer statement of merit criteria
2. Scroll down and observe what happens with the sidebar

![Screenshot 2022-12-19 at 1 00 06 PM](https://user-images.githubusercontent.com/38330843/208490703-fed58783-ca00-4d46-9c91-8d6df347fe9b.png)

**Comment by ClementineHahn** [comment]
Closing as problem was not reproduced nor prioritized .
