### ISSUE TITLE
Enable entry-links of content type: 'Topic'

### ISSUE THREAD

**Issue by dylanzheng94** [cds-snc/resources-ressources#364]
## 📇 User story

As a content designer, I want to use entry-links of type: topic in Contentful, so that I can link to various topics within the rich text body of a page.

## ✅ Definition of Done
- [x] Acceptance criteria met
- [x] Code is peer-reviewed
- [x] Preview is peer-reviewed

## 📜 Acceptance criteria
- [x] Entry-links of type: 'Topic' are implemented in code
- [x] User is able to navigate to a topic, inline within the rich text body of a page

**Comment by anikbrazeau** [comment]
Possible to also consider including the possibility of entry-links for "Collections", "About", "Contact" and "Legal Pages" while we're at it?

**Comment by dylanzheng94** [comment]
Done
