### ISSUE TITLE
Optimize jump-links for mobile (jump-links 2.0)

### ISSUE THREAD

**Issue by dylanzheng94** [cds-snc/resources-ressources#371]
As a user I would like to see and access the table of contents aka jump links as I scroll even on mobile.

**Comment by ClementineHahn** [comment]
Demo before and after implementation of jump link for mobile 

![Image](https://user-images.githubusercontent.com/23077793/217926244-3d31072f-372a-4b72-8866-d0e4f9a4064c.png)
