### ISSUE TITLE
Specificity opportunities and corresponding dependencies/blockers

### ISSUE THREAD

**Issue by janicelagiorgia** [cds-snc/resources-ressources#375]
## Add more details to specificity opportunities doc

- Meet with subject matter experts to frame/identify opportunities
- Scope out feasibility of proposed solutions
- Start implementing changes

https://docs.google.com/document/d/1slAsbDjgajoUCacmgWHppCKZ21GmDdk8Jx6qHqJhLac/edit?pli=1#

Additional/not sure and need to clarify with Anik:
- How we'll add to Figma eventually
- Use screenshots of site
- Map opportunities on user flows

**Comment by anikbrazeau** [comment]
Anik working on subcards below: 

- [Homepage](https://github.com/orgs/cds-snc/projects/16/views/2?filterQuery=&pane=issue&itemId=18933251)
- [Topic: Human-centred design](https://github.com/orgs/cds-snc/projects/16/views/2?filterQuery=&pane=issue&itemId=18697340)
- [Resource: Content design at CDS](https://github.com/orgs/cds-snc/projects/16/views/2?filterQuery=&pane=issue&itemId=18697314)
- [Resource: Service design at CDS](https://github.com/orgs/cds-snc/projects/16/views/2?filterQuery=&pane=issue&itemId=18697310)
- [Resource: Interaction design at CDS](https://github.com/orgs/cds-snc/projects/16/views/2?filterQuery=&pane=issue&itemId=18697323)
- [Topic: Agile development](https://github.com/orgs/cds-snc/projects/16/views/2?filterQuery=&pane=issue&itemId=18697405)
- [Topic: Accessibility](https://github.com/orgs/cds-snc/projects/16/views/2?filterQuery=&pane=issue&itemId=18934651)

**Comment by ClementineHahn** [comment]
Demoed end of Sprint 3, @ClementineHahn to add notes related end of sprint
