### ISSUE TITLE
Update documentation: contentful previews, github PR's and releases

### ISSUE THREAD

**Issue by daine** [cds-snc/resources-ressources#386]
## 📇 User story

As a developer, I want to the technical documentation to be up to date, so that it will be easier to read and work on the product.

## ✅ Definition of Done

- [x] Documentation reviewed by one other team member
- [ ] ~~Documentation exists for french & english (help from @ClementineHahn)~~ Moved to #413

## 📜 Acceptance criteria

- [x] [Contentful Previews in wiki](https://github.com/cds-snc/resources-ressources/wiki/Contentful-Previews)
- [x] Open ticket for: #413
- [x] [Github PRs documentation (squashing commits)](https://github.com/cds-snc/resources-ressources/wiki/Github-workflows)
- [x] [Github Releases documented](https://github.com/cds-snc/resources-ressources/wiki/Github-workflows)

**Comment by ClementineHahn** [comment]
Still missing french translation of feature toggles. @ClementineHahn failed to complete in time. Leftover task to be converted as a new separated card to send tech doc to translation office
