### ISSUE TITLE
Share more of my own content (notes, decks, etc) related to design topics (to add specificity)

### ISSUE THREAD

**Issue by emanelfy** [cds-snc/resources-ressources#388]

**Comment by anikbrazeau** [comment]
Thank you for sharing a ton of notes and decks! 

These have also been documented throughout [Design topic notes](https://docs.google.com/document/d/1vjkXDhF1e_7YKyV7ZCIwXzsnoCWAJNFo5glwrb7fwms/edit#) and also extracted into our [content sources AirTable](https://airtable.com/appycTLaOgPCVlTIj/tbl1z7u3FUmN8e1GT/viwA3jFLWB15e3GoS?blocks=hide). 

Here is a shortlist of outstanding ones that were mentioned, if they happen to be easy enough to locate/share: 

1 - Retiring projects (SDN Global 2022)
2 - Old documentation on differentiating between POR and user research (Online Quiz)
3- In-situ accessibility testing (Carleton)
4- Deck about user mindsets
