### ISSUE TITLE
Avoid "LR"/"RA" acronym in header

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#408]
**Describe the bug**

Rethink narrow header as acronym is
- not meaningful to users
- might mean labour relations in English
- causes confusion in French

**To Reproduce**
1. Go to staging
2. Narrow screen

**Expected behavior**
Full name spelled out, if possible

**Screenshots**

<img width="497" alt="Screenshot 2023-02-09 at 3 32 59 PM" src="https://user-images.githubusercontent.com/38330843/217931006-d378310b-5ba0-4cff-8d12-b0a5a1fad27b.png">

<img width="483" alt="Screenshot 2023-02-09 at 3 32 50 PM" src="https://user-images.githubusercontent.com/38330843/217931015-4391c09a-7f07-4e35-99bd-aab44fce325f.png">

**Comment by dylanzheng94** [comment]
Done - removed acronym
