### ISSUE TITLE
Product documentation available in french

### ISSUE THREAD

**Issue by daine** [cds-snc/resources-ressources#413]
📇 User story
As a developer, I want the technical documentation on feature flags to be bilingual, so that it is easier for bilingual developers to work on the product

✅ Definition of Done
- [ ] Documentation sent to translation and reviewed by a team member

**Comment by daine** [comment]
Grooming notes: Turn around time for linguistic services: a week - 2 weeks or beyond

**Comment by ClementineHahn** [comment]
Changing the scope of the card from 1 doc to translate to all wiki product related doc to translate. 
From "Feature toggles: remaining documentation available in french" to **Product documentation available in french**

**Comment by ClementineHahn** [comment]
Translation ask submitted through form today. 
All content to be translated had been gathered in 1 doc + link to source [here](https://docs.google.com/document/d/1lggN3uGRzSJi0HFWGp8lGpUXPL96DH11d8KdmClFOhI/edit#)

**Comment by ClementineHahn** [comment]
Still pending translation but service has received news about being wrapped up. So translation wont be implemented
