### ISSUE TITLE
Integrate Delighted for feedback

### ISSUE THREAD

**Issue by dylanzheng94** [cds-snc/resources-ressources#422]
## User story

As a stakeholder, I want to have a way of collecting feedback from users to determine the helpfulness of resources on the website so that we have insights for iteration and enhancements

## Definition of Done
- [ ] Code is peer reviewed
- [ ] Feature is available in staging
- [ ] Documentation on feedback widget customization and usage is in Github Wiki

## Acceptance criteria
- [ ] Feedback widget is visible on a webpage
- [ ] Feedback widget is able to collect feedback / user is able to submit feedback
- [ ] Feedback dashboard is able to display collected feedback
- [ ] Feedback widget can be disabled or enabled by a feature flag

**Comment by anikbrazeau** [comment]
Curious whether any bilingual content support might be needed? Always happy to help, if so!

**Comment by hillaryl** [comment]
I think I found a minor limitation with Delighted that doesn't render it unusable, but may be worth considering:

Our goal is to ask a question about how helpful a page is with a binary response. We'll use the negative responses to flag pages that might have clarity or usability issues, and positive responses to gauge which resources are having the most impact.

Ideally we would design the survey item like this:
"Was this page helpful?"
"Yes" / "No"
if response is "No", then: "What were you looking for?" or "What was missing" (still working on the follow up)

Delighted has a binary thumbs up / thumbs down icon pattern, but no "Yes" / "No" option. So it would be:
"Was this page helpful?"
👍 / 👎 
if response is 👎, then:  "What were you looking for?" or "What was missing" (still working on the follow up)

👍 / 👎  has a more ambiguous meaning. It could be read as "yes" or "no", but also "good" / "bad" and has potentially implies more emotion as a reaction than a simple yes or no ("good, I'm happy" / "bad, I'm not happy"). This would introduce a bit of ambiguity around how people are answering the question vs. how we're interpreting it.

I think the main priority should be getting some kind of feedback collection in place over making it perfect, but if we encounter other problems with Delighted we may want to consider something that allows for "yes" / "no" when searching for another tool.

**Comment by ClementineHahn** [comment]
Based on acceptance criteria review (mechanism to display and propose feedback mechanism to user) , decision is t to *not* implement Delighted
