### ISSUE TITLE
Add Learning Resources domain to CDS website's security notice

### ISSUE THREAD

**Issue by dylanzheng94** [cds-snc/resources-ressources#425]
## 📇 User story

The Learning Resources domain needs to be added to the CDS Security Notice because this informs the public that an vulnerability found within the Learning Resources website should be reported to CDS.

## ✅ Definition of Done
- [x] Inform the policy team of the Learning Resources domain to be added

## 📜 Acceptance criteria
- [x] The Learning Resources domain is present in the [CDS Security Notice](https://digital.canada.ca/legal/security-notice/)

**Comment by ClementineHahn** [comment]
Dependency, waiting for Caitlin come back from vacay to progress on this

**Comment by ClementineHahn** [comment]
resources.alpha.canada.ca is now added to the CDS security notice , as visible here [
](https://digital.canada.ca/legal/security-notice/)
![Image](https://user-images.githubusercontent.com/23077793/224800327-5b23017c-ae7f-46c9-b831-ad25320c8736.png)
