### ISSUE TITLE
Embedded assets in contentful

### ISSUE THREAD

**Issue by daine** [cds-snc/resources-ressources#435]
## 📇 User story

As a contentful user, I want to add and embed media assets to content in contentful, so that they get generated and appear on the website.

## ✅ Definition of Done
- [x] Code is reviewed and tested
- [ ] Documentation exists in the Wiki

## 📜 Acceptance criteria
- [x] An image can be added to a contentful entry and it shows up on the website

**Comment by daine** [comment]
We need to add to our content security policy to load images (see error screenshot below on preview.resources.cdssandbox.xyz 

![Image](https://user-images.githubusercontent.com/916044/227252412-090bf56d-1b14-4427-8c6b-bb56b67f7e06.png)

**Comment by ClementineHahn** [comment]
Task stopped as Learning resources service is winding down, even though the embedding of assets was prepped and made possible thanks to good work from @daine . 
We then close this without completion of task
