### ISSUE TITLE
Assess visual design needs

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/resources-ressources#438]
**Goal** : assess our visual design needs so that we can identify what visuals could , should be implemented in Learning Resources website in order to maximize its impact into helping learning to reach its users. 

**Context :** as we unblock the technical feasibility of embedding visuals, prepping in advance our knowledge of design needs will help us better prioritize further task and discover if any extra work to create, tranlate, make accessible designs are needed. All this will reinforce more future prioritization This will help us prioritize the visual design work that needs to be done once the technical feasibility is unblocked.

**Acceptance Criteria:**
Analyze the current visual design of our website
Review Usability testing and context in which visual design needs were suggested 
Document the visual design changes to be made , the reasoning behind them and scope a minimum feasible set (1 sprint /time)

**Done when:**

The analysis of visual design needs changes is share back with team 
Any exissting known necessary design assets (e.g. graphics, icons) are identified and documented for future use 
Any non-existing but necessary design assets are identified and related tickets are created accordingly

**Comment by daine** [comment]
Related to #435

**Comment by anikbrazeau** [comment]
Curious about this issue 👀 

In case it's related to the essence — adding a content perspective:

> Enabling visuals and other multimedia could help enhance a number of current and future resources by supplementing and adding dimension to text-only resources, ultimately helping us better meet the needs of users with different ways of learning. 
>
> Examples of areas where we might anticipate that illustrating a concept could help include: 
> - Iterative product lifecycle phases
> - Multidisciplinary team composition
> - Before and after screenshots to demo product differences
> - Process and architecture diagrams
> - Mapping (roadmaps, blueprints, journeys, etc.)
> - Symbols and iconography

**Comment by ClementineHahn** [comment]
Yes Anik ! its exactly that.  Thank you for that first list <3 

I'd like to review usability testing results + engage with designers on illustration needs and where it could have more impact then triage it all based on impact and feasibility. 
Goal is *not* to create or implement it now , but get ready while we unblock the technical feasibility of triaging what we could down the line, starting with any outstanding quick win and prepping bigger work in parallel if needed.

**Comment by ClementineHahn** [comment]
Working currenlty here[ ](https://docs.google.com/document/d/18Cw-7n1xSHimvi95-wIo4L8WVQOY31OjOViBp541iTU/edit#)

**Comment by anikbrazeau** [comment]
Related: #457

**Comment by ClementineHahn** [comment]
Anik flag that we could considering visuals that are not inherently images : we could have visual style boxes, quote, enhancement, that will add consistent structure and reinforce the content. So far Clementine did not thought about it and could add it.

**Comment by ClementineHahn** [comment]
After consideration, visual needs potential prioritization is tackled here, but will not go forward on the product due to winding down the service.[ ](https://docs.google.com/document/d/18Cw-7n1xSHimvi95-wIo4L8WVQOY31OjOViBp541iTU/edit#heading=h.yj96lzx6gqp2)
