### ISSUE TITLE
Enable embedding of external links within the body content to allow contextualization/rationale 

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#441]
## 📇 User story

As a user, I want to access supporting examples within the relevant section, near related substance/body text, so that I know what is interesting/helpful/relevant once I jump away from the site and know what to expect, what to look for, or how to use an external resource.

As a content designer, I want to link to CDS blogs and product documentation (and potentially other external links) **within the body text,** so that I can better set up, contextualize and rationalize the jump away from the site for users.

**Comment by ClementineHahn** [comment]
Issue redundant with work on enhancing resources that was tackled and done. Therefore closing this issue as work is tracked elsewhere and and a topic by topic approach
