### ISSUE TITLE
Assess what connections exist between all our repos and make updates to READ.MEs/Wikis to link them up

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#451]
✨ Context 

Based on [dev-design sync](https://docs.google.com/document/d/1lbfLgzoPuCveeAS_tiGh6YzUkwrBuXwzi_bxVm8okjw/edit#bookmark=kix.8z9ujbf05w96) we decided to further solidify documentation that makes all the different repos clear and available, especially from the starting point of `resources-ressources` repo, but also making links back to that central repo from discipline-specific repos.

📇 User story 
As a potential stakeholder in this space (internal at CDS or external within the digital or learning ecosystem), I want to understand what's been done and what's been learned, so that I might understand and apply some of the progress and/or insights in future work.

## ✅ Definition of Done

- [ ] Assess repos:
   - main
   - content
   - research
   - devops
   - any others?

- [ ] Make updates:
   - main
   - content
   - research
   - devops
   - any others?

## 📜 Acceptance criteria
- [ ]

**Comment by ClementineHahn** [comment]
Service is winding down, this work therefore is not prioritized anymore. Closing this issue without resolution
