### ISSUE TITLE
Explore feedback integration using Freddy Feedback

### ISSUE THREAD

**Issue by dylanzheng94** [cds-snc/resources-ressources#452]
## 📇 User story

As a stakeholder, I want to explore Freddy Feedback as a feedback mechanism, so that we can make an informed decision on the tool to use for feedback collection.

## ✅ Definition of Done
- [ ] 

## 📜 Acceptance criteria
- [ ]

**Comment by ClementineHahn** [comment]
Exploration is finished but still need for @dylanzheng94 to document decision and update ticket accordingly to track decision back

**Comment by ClementineHahn** [comment]
Privacy policy of Freddy Feedback has been found to be not compliant with acceptance criteria. They have no current privacy policy at play, product seems to be unmaintained and we cant have information about data location and/or mangement. This is a blocker. Freddy feedback is excluded therefore as a potential option for a feedback component and we are not going forward with implementing it.
