### ISSUE TITLE
Resource visual elements to consider

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#457]
## 📇 User story

As an end user (learner), I want to scan resources more easily (with visuals and other elements presented for differentiation/emphasis), so that I can understand/learn concepts more easily (in multiple ways and modalities).

## Possible options to consider

- About/Context (separate visual treatment to differentiate it from resource content)
- Definitions (predictable component or treatment to allow for faster scanning)
- In-line external links (set expectations that will be taken away from site, open in new tab) 
- Bullet hierarchy and styling (possibly considering checklists as an option) 
- Quote (block or treatment to separate from other body text) 
- Boxes or separation for emphasis of examples
- Images or preview of embedded assets (png, Figma, Miro, etc.)

**Comment by anikbrazeau** [comment]
Related issues: #191 #247 #296

**Comment by ClementineHahn** [comment]
Issue was not prioritized and service is winding down, therefore closing this issue without resolution.
