### ISSUE TITLE
Improve site navigation with menu (and possibly groupings for multiple ways?)

### ISSUE THREAD

**Issue by dylanzheng94** [cds-snc/resources-ressources#62]

**Comment by anikbrazeau** [comment]
We might consider grouping similar artifacts to provide people with "multiple ways" of navigating resources.

For example: a grouping/bank of all job postings, or a grouping/bank of all responsibilities, or of all SOMCs, etc.

**Comment by daine** [comment]
Related to #236?

**Comment by dylanzheng94** [comment]
Closing issue as it appears this has been addressed with menu feature developed ( #236 )
