### ISSUE TITLE
Learners have difficulty finding the level of specificity they need

### ISSUE THREAD

**Issue by hillaryl** [cds-snc/resources-ressources#71]
For **participants with the goal of understanding an unfamiliar role** finding high-level, general information is the priority. 

- The volume and brevity of the information under Experience, Knowledge, and Abilities headings on the SOMC page was helpful for getting a general overview of the product management role

- The short descriptions of under "Different types of designers" on the main Designer page were helpful for understanding sub-disciplines, but because they were above the resources below, it led one participant to think that those resources would also be broken down by each sub-discipline. They were briefly confused about which information applied to which discipline

For **participants with the goal of communicating the requirements for a role they're already familiar with** finding specific details that they can re-use is the priority.

- Organization in competencies section helpful: what the competency is, the specific applications for the role and then detailed description: would use specific wording from description here and from SOMC in things like work descriptions
- Responsibilities list helpful for showing credibility of role differentiation for HR

Recommendations
-----

- Apply consistent logic to where general vs. specific information is located on pages and across pages. E.g. more general links and content at top, more specific below
- Use headings to show hierarchy within section (more general = H2, more specific and related to above = H3)

**Comment by anikbrazeau** [comment]
Some interventions underway and captured here: https://trello.com/c/zY454rXp/290-issue-learners-have-difficulty-finding-the-level-of-specificity-they-need

Expansion to every subtype of design and every level of position may have to wait until a future iteration.

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High-priority GitHub issues before launch](https://trello.com/c/rVY120dI/325-high-priority-github-issues-before-launch)

**Comment by anikbrazeau** [comment]
Checklist:

Reorder the page to start with a general definition, directory to other links, followed by more specific secondary information

Adjust logic and hierarchy to go two levels deep (L1=hiring, L2=role, L3=artifact)

Adjust breadcrumbs to go two levels deep only

Add design specializations below (to expand in future)

Adjust SOMC bilingualism -- removing English Essential

Emphasize UX or human-centred design roles

Expand on types of designers: service, content, and interaction designers

Description: break down for different types of designers

Job postings: break down for different types of designers

SOMC: break down for different types of designers

**Comment by hillaryl** [comment]
Trying to determine if the current iteration needs further testing. Right now links to types of designers appear before hiring resources for general designers. This might resolve the issue, but we would need to test it since the specific roles may impact expectations for what's contained in the resource links.

@ClementineHahn @anikbrazeau Are we planning to add sub-discipline specific resources in the near future? And within what timeframe? If it's >3 months an interim fix might be to add "general" to the titles of designer hiring resources so that it's clearer what's behind the link.

If we're deprioritizing adding those resources, I'll plan to test the current solution in a future round of testing to see if there's still confusion.

**Comment by anikbrazeau** [comment]
I think we could add job descriptions and statement of merit criteria for the more specific three sub-types of designers, pretty imminently, in the next week or two if that helps address some of the concerns of this medium-priority issue.

**Comment by ClementineHahn** [comment]
Need to rescope the card to make sure its very to the point of the feedback of sub roles of designers . @emanelfy have context on it to help rescope the card, @hillaryl can help guard rails to make sure its not too large

**Comment by anikbrazeau** [comment]
Partially addressed by broken down card: #338

**Comment by anikbrazeau** [comment]
Exploring possible resource structure here: https://www.figma.com/file/AVmCvoB3Xg7tX5iRDdPNC2/Alpha-II?node-id=167%3A363&t=ButvVOIAcbGJbdy8-4

**Comment by hillaryl** [comment]
Closing this issue as it's quite broad and has been addressed by several interventions. If related issues come up in future testing we can integrate these finding into a new more specific issue then.
